i have made all the recommended changes.Mistakenly, i had closed the previous pull  request.
marsiitr/Fetching-Bot-Rooh- pull request #2
Opened 2020-07-31 12:19 UTC by bhavesh0902

2020-08-01 14:03 UTC, SanjeevKrishnan requested changes
@bhavesh0902 Minor Changes
1. You were asked to add "Models and Robotics Section", and its logo in Report, not in README.md. Remove it from README.md and add it in Report.
2. Try to use cropped images in README.md Your screenshot has other unnecessary elements which is degrading the quality of your README file.

2020-08-01 14:03 UTC, SanjeevKrishnan commented on README.md
> +## Srishti 2020
Make "Srishti 2020" as normal text, not as heading.

2020-08-01 14:03 UTC, SanjeevKrishnan commented on README.md
> +![Final Product](https://github.com/bhavesh0902/Fetching-Bot-Rooh-/blob/master/Images%20and%20Videos/Images/Flowchart%20final.jpg)
Flowchart has to come under second-level heading "Workflow"

2020-08-01 19:14 UTC, bhavesh0902 commented
@SanjeevKrishnan  
Sir, I have made all the recommended changes.

2020-08-02 02:48 UTC, SanjeevKrishnan approved these changes
@bhavesh0902 PR looks fine!
@Shubhanshu07 I suggest for merge.

2020-08-02 14:27 UTC, Shubhanshu07 commented
@bhavesh0902 PR looks good to  me also

2020-08-02 14:27 UTC, merged